version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: computer-science-project20-frontend:latest
    environment:
      - SERVER_URL=https://api.amongbots.illustrates.dev
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/.env.local:/app/.env.local:ro
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_URL=https://amongbots.illustrates.dev
      - TOXICITY_URL=https://toxicity.amongbots.illustrates.dev
      - SUBMIT_DURATION_MS=45000
      - VOTE_DURATION_MS=30000
      - LOG_LEVEL=info
    networks:
      - app-network

  toxicity:
    build:
      context: ./toxicity/ai-service
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    networks:
      - app-network
# REVERSE PROXY
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - toxicity
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

